### ISSUE TITLE
Chapter 8 - UriEndpointComponent deprecated

### ISSUE THREAD

**Issue by imranrazakhan** [camelinaction/camelinaction2#104]
Hi,

 As UriEndpointComponent is deprecated chapter * should be update accordingly.

public class MyComponent extends UriEndpointComponent {

Regards

**Comment by davsclaus** [comment]
Yeah @janstey will do this

**Comment by janstey** [comment]
Fixed with https://github.com/camelinaction/camelinaction2/commit/08899d57616f50503cd50708abe8caf29ba6f85d
