### ISSUE TITLE
Chapter 18 - 18.3.2 Calling a service running inside Kubernetes cluster - Typo and Query

### ISSUE THREAD

**Issue by imranrazakhan** [camelinaction/camelinaction2#107]
Hi,

While reading section 18.3.2 Calling a service running inside Kubernetes cluster
it says 
kubectl expose deployment hello-world --type=NodePort --name=hello-service
"This command exposes a service on the hello-world deployment of type NodePort. Because we
run the Kubernetes cluster using Minikube as a single-node cluster for development purposes,
all we would need is a way to forward network connections from the Kubernetes master to
port 80080 on the running pod. Figure 18.3 illustrates the players involved when you would
call the service from your web browser."

Two concerns
1 - Typo i think port would 8080 rather than 80080
2- what would happen if master goes down? do other nodes(pods) still provide services and second how external client would able to access service after master crash?
Regards

**Comment by davsclaus** [comment]
Ad 1)
Thanks that has been corrected.

Ad 2)
Read Kubernetes in Action. You need the masters to be HA and therefore you setup N+ number of nodes for masters and ensure there is a quorum of them running. If master is going down, then the cluster becomes doomed and external clients cannot call your services. How all that works and so on is out of scope for this book, and you need to find Kubernetes books or online resources on that.
