### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by rajaxyz** [camelinaction/camelinaction2#109]
Dear Claus,
  I sent a mail to claus.ibsen@gmail.com  with brief route and log.If you can't find my mail in inbox, kindly check spam.Sorry to post it in here. Im not sure whether you received my mail or not.So I Post it in here.
Thank you.

**Comment by davsclaus** [comment]
To get help about Apache Camel then see here
http://camel.apache.org/support.html

This place is about the Camel in Action book. So please keep issues only about the book.
