### ISSUE TITLE
cluster-file-infinispan uses active/passive mode

### ISSUE THREAD

**Issue by Vikrammsc** [camelinaction/camelinaction2#121]
First of all the Camel In Action 2 is a must have book for all starters who started learning camel. Recently bought this book its an Awesome book.

I have setup the infinispan server and running that as described in the chapter 17 Readme.md file. 

You have clearly specified the steps running in domain mode with Clustered active/passive mode using Infinispan. Just curious though whether the same can be done with : 

1. Standalone mode instead of using Domain Mode
2. Any Example to run the Active/Active Mode

**Comment by davsclaus** [comment]
Hi

Ad 1)
From Camel point of view, then whether you run infinispan in domain or standalone mode does not really matter. So yeah you should be able to do that.

Ad 2)
The point of this example/section in the book is to have a active/passive use-case where only a single instance is active at any given time.

In chapter 12 there is an example of using hazelcast (but I dont see a reason why Infinispan cannot do this also) in an active/active mode as a clustered indempotent repo for active nodes processing files from a shared folder: https://github.com/camelinaction/camelinaction2/tree/master/chapter12/hazelcast

**Comment by Vikrammsc** [comment]
Thanks for the response. 

I tried the instructions as described below for setting up infinispan repository

https://github.com/apache/camel/tree/master/examples/camel-example-spring-boot-infinispan

I dont want to run camel as a standalone application. Is there a way to change the standalone application in the link above to a Spring boot application. With the Spring Boot camel application i am facing difficulty in :

1.  Bind the repository to spring boot application and
2.  Add Routes to the Application.

main.bind("myRepo", repo);
main.addRouteBuilder(new FileConsumerRoute("BAR", 100));

Can you please help me on getting over this issue or any reference to read to make this work

**Comment by davsclaus** [comment]
I suggest you read the chapter on microservices which covers Camel on Spring Boot. It shows how to add routes. And to bind to repo, you just do it the standard spring boot way via `@Bean("myRepo")` method.
