### ISSUE TITLE
Maven build issue

### ISSUE THREAD

**Issue by ylicode111** [camelinaction/camelinaction2#125]
I ran into the following error when trying to build the code from the top level:

Failed to execute goal org.apache.camel:camel-api-component-maven-plugin:2.21.1:fromApis (generate-test-component-classes) on project hi-world: Error generating source for camelinaction.api.HiWorldJavadocHello: No public non-static methods found, make sure Javadoc is available as project test dependency

Can you please advise how to fix the issue?

**Comment by davsclaus** [comment]
Can you provide more details what you do, eg what source code, and what command do you execute from which directory.

**Comment by davsclaus** [comment]
Closing stale tickets

**Comment by jikechao** [comment]
I come across this problem when I run the commend：“mvn compile”, could you tell me how to solve it, thanks a lot.
