### ISSUE TITLE
mvn test fails [spark-rest]

### ISSUE THREAD

**Issue by zirconias** [camelinaction/camelinaction2#131]
when trying to run project  tests,    it fails in spark-rest,   tests are down except `testCreateOrder`.

the reason is ` connection refused`

**Comment by davsclaus** [comment]
Yeah this can maybe be a little bit flaky due java spark may not shutdown used network ports so you can get a connection refused when another test attempts to use the same port.

What OS are you using?

**Comment by zirconias** [comment]
i'm using ubuntu 18.04, java 8 u191.
