### ISSUE TITLE
Chapter 19 - Add VS Code based Camel tooling

### ISSUE THREAD

**Issue by apupier** [camelinaction/camelinaction2#142]
it might be interesting to provide information on VS Code based tooling in Chapter 19 - Tooling
https://github.com/camelinaction/camelinaction2/tree/master/chapter19

for reference:
the "top-level" extension pack: https://marketplace.visualstudio.com/items?itemName=camel-tooling.apache-camel-extension-pack 
short video of some of the capabilities: https://www.youtube.com/watch?v=okyaqCx6Pz0&feature=youtu.be (already need to be updated...)

**Comment by davsclaus** [comment]
Hi

As the book is done then we cannot add new future material in the source code, that are not covered in the book. 

When a 3rd edition of the book is in the works then that book will be catching up on all the latest on Apache Camel

**Comment by davsclaus** [comment]
Okay @apupier I added a note in the readme of chapter 19
https://github.com/camelinaction/camelinaction2/tree/master/chapter19#additional-tools

You are welcome to polish and add more links, details for the other tools
