### ISSUE TITLE
Chapter 19 - Add maven test coverage plugin

### ISSUE THREAD

**Issue by apupier** [camelinaction/camelinaction2#143]
it would be nice to add information about this not well-known (yet) tool.
for reference https://dzone.com/articles/apache-camel-route-coverage-tooling-on-the-way

Especially as there is some interesting work on it ongoing or quite new:
- Sonar integration https://issues.apache.org/jira/browse/CAMEL-13345
- Thresold for failing build https://issues.apache.org/jira/browse/CAMEL-13001

**Comment by davsclaus** [comment]
Hi

As the book is done then we cannot add new future material in the source code, that are not covered in the book. 

When a 3rd edition of the book is in the works then that book will be catching up on all the latest on Apache Camel
