### ISSUE TITLE
Struggling to get camel in action filter/xpath examples working

### ISSUE THREAD

**Issue by davesargrad** [camelinaction/camelinaction2#153]
I'm starting to work through the examples in the book. I've found the filter xpath to be difficult to get working. I've tried several iterations at this point. I've also verified my xpath online.

I've tried several variants (starting with the filter on "test attribute" provided in the book). 
![image](https://user-images.githubusercontent.com/48793689/73093775-39e82180-3ead-11ea-8a32-d30c080914d9.png)

![image](https://user-images.githubusercontent.com/48793689/73093867-6ac85680-3ead-11ea-85ee-f15073388fa1.png)

In general, my filter drops all the messages. They make it to the outbox if I eliminate the filter.

I commented out the intial attempt at filtering test orders, and then i tried some other variants. Here is my code. In general, I'd expect files to be placed into outbox if they pass the filter. Yet all my files get dropped and dont make it to outbox.
![image](https://user-images.githubusercontent.com/48793689/73094460-a0ba0a80-3eae-11ea-81d5-0f0db1a34bd4.png)

Here is a filter that i think should work (checking value of an element rather than an attribute)

**The XML (inbox/order4.xml)**
```
<?xml version="1.0" encoding="UTF-8"?>
<person><city>London</city></person>
```

**The route**
```
from("file:data/inbox?noop=true")
                        .log("Received order: ${header.CamelFileName}")
                        .filter().xpath("/person/city='London'")
                        .log("Please process valid order: ${header.CamelFileName}")
                        .to("file:data/outbox");
```

**The logged output**
![image](https://user-images.githubusercontent.com/48793689/73093316-4029ce00-3eac-11ea-8695-1b465137d092.png)

I should see the logged message indicating that order4 is procssed and placed in the outbox, and I should see this file in the outbox. Yet I see neither the log, nor the file.

![image](https://user-images.githubusercontent.com/48793689/73094799-571def80-3eaf-11ea-9d68-c89cb170d723.png)

The actual cat'd content of order4.
![image](https://user-images.githubusercontent.com/48793689/73093369-5e8fc980-3eac-11ea-8521-164694e7d923.png)

The online validation using an [xpath tester](https://www.freeformatter.com/xpath-tester.html#ad-output):

![image](https://user-images.githubusercontent.com/48793689/73093464-93038580-3eac-11ea-9de6-78719f96e0e9.png)

What am I missing?

**Comment by davesargrad** [comment]
Hi @davsclaus 

If you have a few minutes to offer a suggestion, would be greatly appreciated. In the mean time, I am enjoying your book.

**Comment by davesargrad** [comment]
My issue was the way I was creating Uber jars.. I now have filtering working. See solution [here](https://stackoverflow.com/questions/59935008/why-does-the-camel-to-route-fail).

**Comment by davsclaus** [comment]
Good to hear you got it working.

See also this FAQ on the Camel website
https://camel.apache.org/manual/latest/faq/how-do-i-use-a-big-uber-jar.html
