### ISSUE TITLE
Struggling to get other seemingly simple camel routes working.

### ISSUE THREAD

**Issue by davesargrad** [camelinaction/camelinaction2#154]
So I've posted this concern on stackoverflow. I wont repeat all the details here, but I do think its the kind of presumably simple route that a book like camel in action should help with. 

As I was going through the books examples, and i started with the FTP -> JMS route, I thought I'd first to FTP -> FILE. Having already done FILE -> FILE, I figured the only new part would be FTP. However it turns out that I got the SFTP component working, yet the FILE destination that I had used in FILE -> FILE no longer worked

Here is my post on [stack](https://stackoverflow.com/questions/59935008/why-does-the-camel-to-route-fail).

**Comment by davesargrad** [comment]
I did receive a proper answer to my post on stack

**Comment by davsclaus** [comment]
Thanks closing this
