### ISSUE TITLE
mvn camel:run fails on spring projects

### ISSUE THREAD

**Issue by johnpoth** [camelinaction/camelinaction2#155]
java.lang.ClassNotFoundException: org.apache.camel.spring.Main
at java.net.URLClassLoader.findClass (URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass (ClassLoader.java:418)
at java.lang.ClassLoader.loadClass (ClassLoader.java:351)
at org.apache.camel.maven.RunMojo$1.run (RunMojo.java:498)
at java.lang.Thread.run (Thread.java:748)

Thanks @clovis-redhat for reporting the issue !

See https://issues.apache.org/jira/browse/CAMEL-14493

Reverting to 2.24.2 solves the issue (or wait for a new release). Thanks !

**Comment by qdo-se** [comment]
I had the same issue when running `mvn clean compile camel:run` in chapter2/spring directory. 

I am using Ubuntu 18.04 and Java 11 OpenJDK. 

I had to downgrade to `camel-version` 2.24.2 and Java 8 OpenJDK for it to work.

If you are using Java 11, you will get this error: https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by tnrangwi** [comment]
> Reverting to 2.24.2 solves the issue (or wait for a new release). Thanks !

Thanks a lot for pointing this out.
