### ISSUE TITLE
Chapter 2.   FtpToJMSWithDynamicToTest throws Exception

### ISSUE THREAD

**Issue by pabs2001** [camelinaction/camelinaction2#158]
java.util.concurrent.RejectedExecutionException
	at org.apache.camel.component.jms.JmsProducer.process(JmsProducer.java:144)

If I replace           _**toD("jms:${header.myDest}")**_    with   _**recipientList(simple("jms:${header.myDest}"))**_
it works,
It works without changing code if I use Camel 3.2.0

**Comment by davsclaus** [comment]
Cannot reproduce this with Camel 3.14.x
