### ISSUE TITLE
Chapter 7 Errata

### ISSUE THREAD

**Issue by nicdd** [camelinaction/camelinaction2#161]
Should we add to Errata:

Page 272, Second paragraph:
delete -  "... Notice that _@Path_ and _@PathParams_ map to the **partIds** ..."
replace with + "... Notice that _@Path_ and _@PathParams_ map to the **cartIds** ..."

?

**Comment by davsclaus** [comment]
Yes this is correct, thanks for spotting

**Comment by davsclaus** [comment]
Fixed
