### ISSUE TITLE
Chapter-2 Spring

### ISSUE THREAD

**Issue by phaniyannam** [camelinaction/camelinaction2#167]
Camel Version : 2.25.0
Java: 13

Tried: 
1. Added camel-spring dependency to the parent pom. 
2. Fixed jaxb errors with adding them into the parent pom. 
3. Reverting back to 2.24.3 works fine.

Error: 
[INFO] Starting Camel ...
[ERROR] *************************************
[ERROR] Error occurred while running main from: org.apache.camel.spring.Main
[ERROR] 
java.lang.ClassNotFoundException: org.apache.camel.spring.Main
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.apache.camel.maven.RunMojo$1.run(RunMojo.java:498)
	at java.base/java.lang.Thread.run(Thread.java:830)
[ERROR] *************************************

**Comment by davsclaus** [comment]
Yeah that is a issue in that 2.25.0 release, try newer 2.25.x

**Comment by phaniyannam** [comment]
Thank you @davsclaus

**Comment by davsclaus** [comment]
The master branch is the code back in the time when the book was released.

See the readme on github where it says there are branches for Camel 3.x. You need Camel 3.x to work with Java 11.
Camel 2.x only works with Java 8.

**Comment by davsclaus** [comment]
Ah thanks that example needs camel-spring-main JAR to run

**Comment by davsclaus** [comment]
I have fixed that example now
