### ISSUE TITLE
mvn compile exec:java fails in Chapter1

### ISSUE THREAD

**Issue by Lienix** [camelinaction/camelinaction2#170]
Following error occured: The parent pom could not be resolved from https://repo.maven.apache.org/maven2

$ mvn compile exec:java
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.camelinaction:chapter1:[unknown-version]: Failure to find com.camelinaction:parent:pom:2.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ com.camelinaction:chapter1:[unknown-version], C:\DEV\Camel\camelinaction2\chapter1\pom.xml, line 6, column 11
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.camelinaction:chapter1-file-copy:[unknown-version] (C:\DEV\Camel\camelinaction2\chapter1\file-copy\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.camelinaction:chapter1:[unknown-version]: **Failure to find com.camelinaction:parent:pom:2.0.0 in https://repo.maven.apache.org/maven2** was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ com.camelinaction:chapter1:[unknown-version], C:\DEV\Camel\camelinaction2\chapter1\pom.xml, line 6, column 11 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by davsclaus** [comment]
Do you still have problems with this?

**Comment by davsclaus** [comment]
closing outdated
