### ISSUE TITLE
using log4j2 with Camel and Springboot

### ISSUE THREAD

**Issue by kameshsampath** [camelinaction/camelinaction2#20]
when using log4j2 logging with Camel and Spring boot via `spring-boot-starter-log4j2`, it is required that we need to add `log4j2.xml` instead of `log4j2.properties` as the spring boot log4j2 logger is unable to load `log4j2.properties` resulting in `java.lang.NoSuchMethodError: org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration ...`

**Comment by davsclaus** [comment]
You can configure SB logging in their application.properties / yml file, so I think people tend to configure it there instead

**Comment by davsclaus** [comment]
eg just do: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html
