### ISSUE TITLE
Turn on fastMode by default for VertX examples and cleanup display

### ISSUE THREAD

**Issue by kevinearls** [camelinaction/camelinaction2#26]
Except for serious drinkers, I think it makes for a better demo if we turn fastMode on for the chapter7 vertx example, and add it for the vertx-camel example.  

At the same time it would be nice to update the display by adding :00 to gametime, as this would make it look more like a real scoreboard, and after a goal is scored put the updated score on one line.

**Comment by davsclaus** [comment]
Thanks merged.
