### ISSUE TITLE
[Chapter 1] MVN Issue

### ISSUE THREAD

**Issue by MariuszHxGNMIN** [camelinaction/camelinaction2#30]
Hi I'm reading the book in MEAP version and going step by step and verifying the examples.
So I have tried the chapter 1 mvn compile exec:java -Dexec.mainClass=camelinaction.FileCopierWithCamel.
The results is:
D:\Sandbox\camelinaction2\chapter1\file-copy
PS>mvn compile exec:java -Dexec.mainClass=camelinaction.FileCopierWithCamel
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Camel in Action 2 :: Chapter 1 :: File Copy Example 2.0.0
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.547 s
[INFO] Finished at: 2017-03-30T10:29:22+02:00
[INFO] Final Memory: 12M/491M
[INFO] ------------------------------------------------------------------------
[ERROR] Unknown lifecycle phase ".mainClass=camelinaction.FileCopierWithCamel". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException

**Comment by davsclaus** [comment]
I wonder if you typed something wrong, or made some wrong space. You can copy/paste the command from the readme file.

```
^Cdavsclaus:/Users/davsclaus/workspace/camelinaction2/chapter1/file-copy (master)/$ mvn compile exec:java -Dexec.mainClass=camelinaction.FileCopierWithCamel
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Camel in Action 2 :: Chapter 1 :: File Copy Example 2.0.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ chapter1-file-copy ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ chapter1-file-copy ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ chapter1-file-copy ---
[ion.FileCopierWithCamel.main()] DefaultCamelContext            INFO  Apache Camel 2.18.3 (CamelContext: camel-1) is starting
[ion.FileCopierWithCamel.main()] ManagedManagementStrategy      INFO  JMX is enabled
[ion.FileCopierWithCamel.main()] DefaultTypeConverter           INFO  Loaded 189 type converters
[ion.FileCopierWithCamel.main()] DefaultRuntimeEndpointRegistry INFO  Runtime endpoint registry is in extended mode gathering usage statistics of all incoming and outgoing endpoints (cache limit: 1000)
[ion.FileCopierWithCamel.main()] DefaultCamelContext            INFO  StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
[ion.FileCopierWithCamel.main()] FileEndpoint                   INFO  Endpoint is configured with noop=true so forcing endpoint to be idempotent as well
[ion.FileCopierWithCamel.main()] FileEndpoint                   INFO  Using default memory based idempotent repository with cache max size: 1000
[ion.FileCopierWithCamel.main()] DefaultCamelContext            INFO  Route: route1 started and consuming from: file://data/inbox?noop=true
[ion.FileCopierWithCamel.main()] DefaultCamelContext            INFO  Total 1 routes, of which 1 are started.
[ion.FileCopierWithCamel.main()] DefaultCamelContext            INFO  Apache Camel 2.18.3 (CamelContext: camel-1) started in 0.492 seconds
^Cdavsclaus:/Users/davsclaus/workspace/camelinaction2/chapter1/file-copy (master)/$
```

**Comment by davsclaus** [comment]
@janstey we should consider adding that main class to the exec-java plugin in the pom.xml so people can just type

    mvn compile exec:java

We do this for some of the Camel examples at Apache Camel

**Comment by davsclaus** [comment]
Would be good to make chapter 1 example even easier to run

**Comment by MariuszHxGNMIN** [comment]
Thanks for replay.... I found the answer... the problem was with my default shell... if you execute this in Powershell you need to make it like that 
`mvn compile exec:java "-Dexec.mainClass=camelinaction.FileCopierWithCamel"`
and in CMD 
`mvn compile exec:java -Dexec.mainClass=camelinaction.FileCopierWithCamel`
