### ISSUE TITLE
Chapter7-cart: java.lang.ArrayIndexOutOfBoundsException at org.codehaus.plexus.util.xml.pull.MXParser.parsePI

### ISSUE THREAD

**Issue by felixvolz** [camelinaction/camelinaction2#49]
When running `mvn compile exec:java` on chapter7/prototype/cart I see the following maven error (see maven logs)
I have no issue with any of the prior chapter 7 builds 

[mvn_output.txt](https://github.com/camelinaction/camelinaction2/files/954676/mvn_output.txt)

**Comment by davsclaus** [comment]
I logged a ticket about Maven 3.5.0 which we may not yet use/support in ticket #50

**Comment by davsclaus** [comment]
I upgraded some maven plugins to newer versions. Maybe they work with Maven 3.5.0. I am using 3.2.5, and 3.3.3 should work as well.

**Comment by davsclaus** [comment]
Re-open if you still have a problem
