### ISSUE TITLE
Chapter18 kubernetes/client-spring/pom.xml has extraneous <version>/<version> entry

### ISSUE THREAD

**Issue by kevinearls** [camelinaction/camelinaction2#70]
I cd'd to chapter18/kubernetes/client-spring, and got the following after executing mvn clean install fabric8:run

[kearls@planet-express client-spring]$ mvn clean install fabric8:run
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-actuator:jar is missing. @ line 60, column 16
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.camelinaction:spring-kubernetes:2.0-SNAPSHOT (/home/kearls/sources/books/forks/camelinaction2/chapter18/kubernetes/client-spring/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.springframework.boot:spring-boot-actuator:jar is missing. @ line 60, column 16
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by davsclaus** [comment]
Thanks for the PR
