### ISSUE TITLE
README error in ch18/kubernetes kubernetes log is not displayed after mvn fabric8:run

### ISSUE THREAD

**Issue by kevinearls** [camelinaction/camelinaction2#72]
I followed the instructions in chapter18/kubernetes/README.md, but after deploying the spring client with "mvn clean install fabric8:run" I did not get the log displayed, at least not in real time.   Once I hit ctrl-c then it dumps entire log at once.

This is with minikube v.0.19.0

**Comment by davsclaus** [comment]
Thanks, yeah need to update the chapter when its back from proofing with the latest minikube version, as its output has changed slightly.

**Comment by davsclaus** [comment]
Likely a problem with the fmp plugin. I have upgraded to latest.
