### ISSUE TITLE
Chapter 10 build fails because of duplicate artifactId

### ISSUE THREAD

**Issue by kevinearls** [camelinaction/camelinaction2#80]
mvn clean install in chapter10 produces 

[ERROR] [ERROR] Project 'com.camelinaction:chapter10-spark-rest-json:2.0.0' is duplicated in the reactor @ 
[ERROR] Project 'com.camelinaction:chapter10-spark-rest-json:2.0.0' is duplicated in the reactor -> [Help 1]

This is because both the poms for spark-rest-json and springboot-json contain "<artifactId>chapter10-spark-rest-json</artifactId>"

**Comment by davsclaus** [comment]
Thanks your PR has fixed this
