### ISSUE TITLE
chapter9 - spring-boot 

### ISSUE THREAD

**Issue by imranrazakhan** [camelinaction/camelinaction2#93]
I extend this junit example with one more Test in which file will get transfer to second folder now when i run both tests.  only one get pass for second test it shows null at line
assertTrue(notify.matchesMockWaitTime());  

if i comment one test other get pass
@Test
    public void testMoveFile() throws Exception {
        NotifyBuilder notify = new NotifyBuilder(context).whenDone(1).create();
        template.sendBodyAndHeader("file://target/inbox", "Hello World", Exchange.FILE_NAME, "hello.txt");
        assertTrue(notify.matchesMockWaitTime());
        File target = new File("target/outbox/hello.txt");
        assertTrue("File should have been moved", target.exists());
    }

@Test
    public void testInvalidMoveFile() throws Exception {
        NotifyBuilder notify = new NotifyBuilder(context).whenDone(1).create();
        template.sendBodyAndHeader("file://target/inbox", "Hello Invalid", Exchange.FILE_NAME, "hello.txt");
        assertTrue(notify.matchesMockWaitTime());
        File target = new File("target/invalid/hello.txt");
        assertTrue("File should have been moved", target.exists());
    }

**Comment by davsclaus** [comment]
Sounds like both routes are active and that only one route pickup the file and therefore only 1 test can pass. 

You need to provide more details what you do, eg what 2nd route you added etc.

**Comment by imranrazakhan** [comment]
I add following and all start working
@DirtiesContext(classMode = ClassMode.AFTER_EACH_TEST_METHOD)

Suggestion: Addition of one more class with multiple tests would be nice in github

**Comment by davsclaus** [comment]
See the spring-boot-test-one-route where you can test one route (or a specific set of routes at a time). This is also covered in the book.
